version: "3.9"

services:
  api:
    build: .
    container_name: friday_api
    restart: always
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "80:8000"
    volumes:
      - ./logs:/app/logs

  db:
    image: mysql:8.0
    container_name: friday_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DATABASE_NAME}"
      MYSQL_USER: "${DATABASE_USERNAME}"
      MYSQL_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:6.2-alpine
    container_name: friday_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
