services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${CERT_PATH:-/opt/friday-api/certs}:/etc/nginx/certs:rw
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
    depends_on:
      - api
    networks:
      - proxy-tier

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx_proxy_le
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${CERT_PATH:-/opt/friday-api/certs}:/etc/nginx/certs:rw
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - ${CERT_PATH:-/opt/friday-api/certs}:/etc/acme.sh:rw
    depends_on:
      - nginx-proxy
    networks:
      - proxy-tier
    environment:
      NGINX_PROXY_CONTAINER: "nginx_proxy"
      ACME_CA_URI: "https://acme-v02.api.letsencrypt.org/directory"

  api:
    build: .
    container_name: friday_api
    restart: always
    env_file:
      - .env
    # We remove "depends_on: - db" because there's no local MySQL in this version
    depends_on:
      - redis
    environment:
      - VIRTUAL_HOST=${FRIDAY_DOMAIN}
      - LETSENCRYPT_HOST=${FRIDAY_DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - REDIS_HOST=redis
    volumes:
      - ./logs:/app/logs
    networks:
      - proxy-tier
      - default

  worker:
    build: .
    container_name: friday_worker
    restart: always
    depends_on:
      - redis
    env_file:
      - .env
    command: bash -c "PYTHONPATH=/app python -m infrastructure.queue.run_worker"
    environment:
      - REDIS_HOST=redis
    volumes:
      - ./logs:/app/logs
    networks:
      - default

  redis:
    image: redis:6.2-alpine
    container_name: friday_redis
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - default
    command: redis-server --requirepass ${REDIS_PASSWORD}

networks:
  proxy-tier:
  default:

volumes:
  redis_data:
  nginx_vhost:
  nginx_html:
