version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/friday-api:cached
      - ../logs:/app/logs
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - APP_NAME=Friday API (Dev)
      - API_VERSION=1.0.0
      - DEBUG_MODE=true
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
      - DATABASE_DIALECT=mysql
      - DATABASE_DRIVER=+pymysql
      - DATABASE_HOSTNAME=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=friday_dev
      - DATABASE_USERNAME=friday_dev
      - DATABASE_PASSWORD=friday_dev
      - DATABASE_URL=mysql://friday_dev:friday_dev@db:3306/friday_dev
      - STORAGE_BACKEND=local
      - STORAGE_PATH=/workspaces/friday-api/storage
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_SSL=false
      - REDIS_TIMEOUT=10
      - QUEUE_JOB_TIMEOUT=600
      - QUEUE_JOB_TTL=3600
      - JWT_SECRET_KEY=dev_secret_key_for_development_only
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - CORS_ORIGINS=["*"]
      - CORS_METHODS=["*"]
      - CORS_HEADERS=["*"]
      - PYTHONPATH=/workspaces/friday-api

  worker:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/friday-api:cached
      - ../logs:/app/logs
    command: python -m infrastructure.queue.run_worker
    depends_on:
      - redis
      - db
    environment:
      - APP_NAME=Friday API (Dev)
      - API_VERSION=1.0.0
      - DEBUG_MODE=true
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
      - DATABASE_DIALECT=mysql
      - DATABASE_DRIVER=+pymysql
      - DATABASE_HOSTNAME=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=friday_dev
      - DATABASE_USERNAME=friday_dev
      - DATABASE_PASSWORD=friday_dev
      - DATABASE_URL=mysql://friday_dev:friday_dev@db:3306/friday_dev
      - STORAGE_BACKEND=local
      - STORAGE_PATH=/workspaces/friday-api/storage
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_SSL=false
      - REDIS_TIMEOUT=10
      - QUEUE_JOB_TIMEOUT=600
      - QUEUE_JOB_TTL=3600
      - JWT_SECRET_KEY=dev_secret_key_for_development_only
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - CORS_ORIGINS=["*"]
      - CORS_METHODS=["*"]
      - CORS_HEADERS=["*"]
      - PYTHONPATH=/workspaces/friday-api

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=friday_dev
      - MYSQL_USER=friday_dev
      - MYSQL_PASSWORD=friday_dev
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
