version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/${localWorkspaceFolderBasename}:cached
      - ~/.gitconfig:/home/vscode/.gitconfig
    command: sleep infinity
    environment:
      - PYTHONPATH=/workspaces/${localWorkspaceFolderBasename}
    user: vscode
    ports:
      - "8000:8000"  # For FastAPI development server
    networks:
      - default

  db:
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: friday_dev
      MYSQL_USER: friday_dev
      MYSQL_PASSWORD: friday_dev
    ports:
      - "3306:3306"
    volumes:
      - friday-mysql-data:/var/lib/mysql
    networks:
      - default

  redis:
    ports:
      - "6379:6379"
    volumes:
      - friday-redis-data:/data
    networks:
      - default

volumes:
  friday-mysql-data:
  friday-redis-data:

networks:
  default:
